import React from "react";
import reactBootstrap, {
  Container,
  Alert,
  Button,
  Form,
  Row,
  Col,
} from "react-bootstrap";
const ProductInformationInputSection = (props) => {
  return (
    <Row>
      <Col>
        <Row>
          <Col>
            text
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Col>label</Col>
                </Row>
                <Row>
                  <Col>input</Col>
                </Row>
              </Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>
                <Row>
                  <Col>title</Col>
                </Row>
                <Row>
                  <Col>image</Col>
                </Row>
                <Row>
                  <Col>action</Col>
                </Row>
              </Col>
              <Col>
                <Row>
                  <Col>title</Col>
                </Row>
                <Row>
                  <Col>image</Col>
                </Row>
                <Row>
                  <Col>action</Col>
                </Row>
              </Col>
              <Col>
                <Row>
                  <Col>title</Col>
                </Row>
                <Row>
                  <Col>image</Col>
                </Row>
                <Row>
                  <Col>action</Col>
                </Row>
              </Col>
              <Col>
                <Row>
                  <Col>title</Col>
                </Row>
                <Row>
                  <Col>image</Col>
                </Row>
                <Row>
                  <Col>action</Col>
                </Row>
              </Col>
              <Col>
                <Row>
                  <Col>title</Col>
                </Row>
                <Row>
                  <Col>image</Col>
                </Row>
                <Row>
                  <Col>action</Col>
                </Row>
              </Col>
            </Row>
          </Col>
        </Row>
      </Col>
    </Row>
  );
};

export default ProductInformationInputSection;
