import React from "react";
import reactBootstrap, {
  Container,
  Alert,
  Button,
  Form,
  Row,
  Col,
} from "react-bootstrap";
const TextInputSection = (props) => {
  return (
    <Row>
      <Col>
        text
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
        <Row>
          <Col>
            <Row>
              <Col>label</Col>
            </Row>
            <Row>
              <Col>input</Col>
            </Row>
          </Col>
        </Row>
      </Col>
    </Row>
  );
};

export default TextInputSection;
